services:
  - type: web
    name: winmail
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    ports:
      - port: 80
      - port: 110
      - port: 143
      - port: 25
      - port: 465
      - port: 995
      - port: 993
