services:
  - type: web
    name: winmail
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    envVars:
      - key: PORT
        value: 80
    scaling:
      minInstances: 1
      maxInstances: 1
