services:
  - type: web
    name: winmail
    env: docker
    plan: free
    region: singapore
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "80"
    ports:
      - port: 80
        protocol: TCP
      - port: 25
        protocol: TCP
      - port: 110
        protocol: TCP
      - port: 143
        protocol: TCP
